# Generated by Django 3.2.7 on 2021-10-13 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individuals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('individual_level', models.IntegerField(choices=[(0, 'Player'), (1, 'Parent'), (2, 'Volunteer'), (3, 'Medical'), (4, 'Coach'), (5, 'Clubs'), (6, 'Referee'), (7, 'Organizer'), (8, 'Director')], default=0)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=10)),
                ('ground_name', models.CharField(max_length=100)),
                ('pitch_number', models.IntegerField(default=0)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('refree_name1', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
