# Generated by Django 3.2.7 on 2021-10-30 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='touranment_name',
            field=models.CharField(default='random_tournament', max_length=100),
        ),
        migrations.AddField(
            model_name='matches',
            name='tournament_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='matches',
            name='tournament_id',
            field=models.CharField(default='random', max_length=10),
        ),
        migrations.AddField(
            model_name='matches',
            name='tournament_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
