# Generated by Django 3.2.7 on 2021-11-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20211030_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=20)),
                ('vendor_name', models.CharField(max_length=40)),
            ],
        ),
    ]
